/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion.Main;

import Presentacion.Controlador.Controlador;

import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JPanel;

/**
 *
 * @author gerar
 */
public class MainFrame extends JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        
        //NO se pueda modificar el tamaño
        //setResizable(false);
        
        JMenuBar jMenuBar1 = new JMenuBar();
        JMenuItem jMenuVentas = new JMenuItem("Nueva venta");
        //jMenuVentas.setText("Ventas");
        jMenuVentas.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
                Controlador.getInstancia().accion(null, Controlador.REALIZAR_NUEVA_VENTA);
            }

        });
        
        
        /*JMenuItem menuVerVentas = new JMenuItem("Ver ventas");
        menuVerVentas.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
            	Controlador.getInstancia().accion(null, Controlador.VER_VENTAS);
            }

        });
        jMenuVentas.add(menuVerVentas);
        
        JMenuItem menuNuevaVentas = new JMenuItem("Nueva venta");
        menuNuevaVentas.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
                Controlador.getInstancia().accion(getThis(), Controlador.REALIZAR_NUEVA_VENTA);
            }

        });
        jMenuVentas.add(menuNuevaVentas);*/
        
        jMenuBar1.add(jMenuVentas);
        
        JMenu jMenu1 = new JMenu();
        jMenu1.setText("Administrador");
        
        

        JMenuItem menuSala = new JMenuItem("Salas");
        menuSala.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
                Controlador.getInstancia().accion(null, Controlador.VER_SALAS);
            }

        });
        jMenu1.add(menuSala);

        
        
        
        JMenuItem menuPeliculas = new JMenuItem("Peliculas");
        menuPeliculas.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
                Controlador.getInstancia().accion(null, Controlador.VER_PELICULAS);
            }

        });
        jMenu1.add(menuPeliculas);

        JMenuItem menuSesiones = new JMenuItem("Sesiones");
        menuSesiones.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
                Controlador.getInstancia().accion(null, Controlador.VER_SESIONES);
            }

        });        
        jMenu1.add(menuSesiones);
        
        JMenuItem menuEmpleados = new JMenuItem("Empleados");
        menuEmpleados.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
                Controlador.getInstancia().accion(null, Controlador.VER_EMPLEADOS);
            }

        });        
        jMenu1.add(menuEmpleados);
        
        JMenuItem menuVentas = new JMenuItem("Ventas");
        menuVentas.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
                Controlador.getInstancia().accion(null, Controlador.VER_TODAS_VENTAS);
            }

        });        
        jMenu1.add(menuVentas);
        
        jMenuBar1.add(jMenu1);


        setJMenuBar(jMenuBar1);
        setSize(650, 480);
        ImageIcon img = new ImageIcon("src/Imagenes/cinestar.jpg");
        Icon icono = new ImageIcon(img.getImage().getScaledInstance(this.getSize().width, this.getSize().height, Image.SCALE_DEFAULT));
        labelFondo.setIcon(icono);
        panelPrincipal.setOpaque(false);
    }
    
    public void update(JPanel panel){
        panelPrincipal.removeAll();
        panel.setSize(630, 410);
        panelPrincipal.add(panel);
        panelPrincipal.revalidate();
        panelPrincipal.repaint();
    }
    
    public JFrame getThis(){
        return this;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        labelFondo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        panelPrincipal.setPreferredSize(new java.awt.Dimension(600, 400));

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 629, Short.MAX_VALUE)
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );

        getContentPane().add(panelPrincipal);
        panelPrincipal.setBounds(0, 0, 629, 410);

        labelFondo.setIcon(new javax.swing.ImageIcon("..\\..\\Imagenes\\cinestar.jpg")); // NOI18N
        getContentPane().add(labelFondo);
        labelFondo.setBounds(0, 0, 630, 410);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>                        

    // Variables declaration - do not modify                     
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel labelFondo;
    private javax.swing.JPanel panelPrincipal;
    // End of variables declaration                   
}
