/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion.Empleados;

import Negocio.Empleados.TEmpleado;
import Presentacion.Controlador.Controlador;

import java.util.ArrayList;

/**
 *
 * @author gerar
 */
public class PanelEmpleados extends javax.swing.JPanel {
    TableModelEmpleados tableModel;
    /**
     * Creates new form PanelEmpleados
     */
    public PanelEmpleados(ArrayList<TEmpleado> tEmpleados) {
        initComponents();
        tableModel = new TableModelEmpleados(tEmpleados);
        tableEmpleados.setModel(tableModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableEmpleados = new javax.swing.JTable();
        btnAnadirEmpleado = new javax.swing.JButton();
        btnModificarEmpleado = new javax.swing.JButton();
        btnEliminarEmpleado = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(600, 400));

        tableEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableEmpleados);

        btnAnadirEmpleado.setText("Añadir Empelado");
        btnAnadirEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnadirEmpleadoActionPerformed(evt);
            }
        });

        btnModificarEmpleado.setText("Modificar Empleado");
        btnModificarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarEmpleadoActionPerformed(evt);
            }
        });

        btnEliminarEmpleado.setText("Eliminar Empleado");

        btnEliminarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	btnEliminarEmpleadoEmpleadoActionPerformed(evt);
            }
        });
        
        
        
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEliminarEmpleado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnModificarEmpleado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAnadirEmpleado)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAnadirEmpleado)
                    .addComponent(btnModificarEmpleado)
                    .addComponent(btnEliminarEmpleado))
                .addGap(7, 7, 7))
        );
    }// </editor-fold>                        

    private void btnModificarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {                                                     
        // TODO add your handling code here:
        TEmpleado tEmpleado = tableModel.gettEmpleados().get(tableEmpleados.getSelectedRow());
        Controlador.getInstancia().accion(tEmpleado,Controlador.VER_MODIFICAR_EMPLEADO);
    }                                                    

    private void btnAnadirEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        // TODO add your handling code here:
        Controlador.getInstancia().accion(null,Controlador.VER_ANADIR_EMPLEADO);
    }                                                 
    
    private void btnEliminarEmpleadoEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {                                                     
        // TODO add your handling code here:
    	Integer idEmp = tableModel.gettEmpleados().get(tableEmpleados.getSelectedRow()).getIdEmpleado();
        //TEmpleado tEmpleado = tableModel.gettEmpleados().get(tableEmpleados.getSelectedRow());
        Controlador.getInstancia().accion(idEmp,Controlador.ELIMINAR_EMPLEADO);
    }                                                    


    // Variables declaration - do not modify                     
    private javax.swing.JButton btnAnadirEmpleado;
    private javax.swing.JButton btnEliminarEmpleado;
    private javax.swing.JButton btnModificarEmpleado;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableEmpleados;
    // End of variables declaration                   
}
