/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion.Sesion;

import Negocio.Pelicula.TPelicula;
import Negocio.Sala.TSala;
import Negocio.Sesion.TSesion;

import Presentacion.Controlador.Controlador;


import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.util.ArrayList;
import java.util.Date;

import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author gerar
 */
public class GUIAnadirSesion extends javax.swing.JDialog {
    
    /**
     * Creates new form GUIAnadirSesion
     */
    public GUIAnadirSesion(java.awt.Frame parent, boolean modal,ArrayList<TSala> tSalas,ArrayList<TPelicula> tPeliculas,
                                ArrayList<TSesion> tSesiones,ArrayList<Date> horasDisponibles,TSala tSalaSeleccionada,
                                TPelicula tPeliculaSeleccionada,Date fecha) {
        Controlador ctrl = Controlador.getInstancia();
        
        initComponents();
        
        setSize(615,382);
        for (TSala tSala : tSalas) {
            cbSalas.addItem(tSala);
        }
        cbSalas.setSelectedItem(tSalaSeleccionada);
        
        
        TableModelSesionPorSala tableModel = new TableModelSesionPorSala(tSesiones);
        jTableSesiones.setModel(tableModel);
        
        jTableSesiones.setOpaque(false);
        
        jScrollPane1.setOpaque(false);
        jScrollPane1.getViewport().setOpaque(false);
        
        ImageIcon img = new ImageIcon("src/Imagenes/cinestar.jpg");
        Icon icono = new ImageIcon(img.getImage().getScaledInstance(this.getSize().width, this.getSize().height, Image.SCALE_DEFAULT));
        lblFondo.setIcon(icono);
        ArrayList<Date> horasOcupadas = new ArrayList();
        Date horaFin = null;
        int indice = 0;
        dateFecha.setDate(fecha);
        final JDialog ventana = this;
        dateFecha.addPropertyChangeListener(new PropertyChangeListener(){

			@Override
			public void propertyChange(PropertyChangeEvent arg0) {
				// TODO Apéndice de método generado automáticamente
				if(ventana.isVisible()){
					Object[] datos = new Object[3];
	                datos[0] = (TSala) cbSalas.getSelectedItem();
	                datos[1] = (TPelicula) cbPeliculas.getSelectedItem();
	                datos[2] = dateFecha.getDate();
	                setVisible(false);
	                Controlador.getInstancia().accion(datos, Controlador.VER_ANADIR_SESION);
				}				
			}
        	
        });
        
        
        for (TPelicula tPelicula : tPeliculas) {
            cbPeliculas.addItem(tPelicula);
        }
        cbPeliculas.setSelectedItem(tPeliculaSeleccionada);
       
        txtDuracion.setText(tPeliculaSeleccionada.getDuracion().toString());
        
        
        if(horasDisponibles != null){
            for (Date horasDiponible : horasDisponibles) {
                cbHorasDisponibles.addItem(new DateHora(horasDiponible));
            }
        }
        
        cbSalas.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
                Object[] datos = new Object[3];
                datos[0] = (TSala) cbSalas.getSelectedItem();
                datos[1] = (TPelicula) cbPeliculas.getSelectedItem();
                datos[2] = dateFecha.getDate();
                setVisible(false);
                Controlador.getInstancia().accion(datos, Controlador.VER_ANADIR_SESION);                
            }
            
        });
        
        cbPeliculas.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
                Object[] datos = new Object[3];
                datos[0] = (TSala) cbSalas.getSelectedItem();
                datos[1] = (TPelicula) cbPeliculas.getSelectedItem();
                datos[2] = dateFecha.getDate();
                setVisible(false);
                Controlador.getInstancia().accion(datos, Controlador.VER_ANADIR_SESION);               
            }
            
        });             
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        btnGuardar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cbSalas = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        cbPeliculas = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        txtDuracion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cbHorasDisponibles = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableSesiones = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        spinnerCantLibres = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        tPrecioUnitario = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        dateFecha = new com.toedter.calendar.JDateChooser();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(240, 140, 240));
        getContentPane().setLayout(null);

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar);
        btnGuardar.setBounds(510, 315, 80, 23);

        jLabel1.setText("Sala");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 50, 40, 14);
        getContentPane().add(cbSalas);
        cbSalas.setBounds(50, 50, 160, 20);

        jLabel2.setText("Pelicula");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 80, 50, 14);

        getContentPane().add(cbPeliculas);
        cbPeliculas.setBounds(60, 80, 150, 20);

        jLabel3.setText("Duracion:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 110, 55, 14);

        txtDuracion.setEditable(false);
        getContentPane().add(txtDuracion);
        txtDuracion.setBounds(60, 110, 110, 30);

        jLabel4.setText("Horas Inicio Disponibles:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 150, 140, 14);

        getContentPane().add(cbHorasDisponibles);
        cbHorasDisponibles.setBounds(150, 150, 65, 20);

        jTableSesiones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTableSesiones);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(220, 0, 380, 310);

        jLabel5.setBackground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Cantidad de Plazas Libres:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 190, 130, 14);
        getContentPane().add(spinnerCantLibres);
        spinnerCantLibres.setBounds(140, 186, 40, 20);

        jLabel6.setText("Precio de Entrada Unitario:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 220, 130, 14);
        getContentPane().add(tPrecioUnitario);
        tPrecioUnitario.setBounds(140, 215, 70, 20);

        jLabel7.setText("Fecha:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 20, 33, 14);
        getContentPane().add(dateFecha);
        dateFecha.setBounds(40, 15, 170, 20);

        lblFondo.setIcon(new javax.swing.ImageIcon("C:\\Users\\gerar\\Downloads\\cinestar.jpg")); // NOI18N
        getContentPane().add(lblFondo);
        lblFondo.setBounds(0, 0, 600, 340);

        pack();
    }// </editor-fold>                        

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    	//--
    	TSala tSala = (TSala) cbSalas.getSelectedItem();
        TPelicula tPelicula = (TPelicula) cbPeliculas.getSelectedItem();
        Date hora = (Date) cbHorasDisponibles.getSelectedItem();
        Date fecha = dateFecha.getDate();
        Integer cantLibres = (Integer) spinnerCantLibres.getValue();
        String precioUni = tPrecioUnitario.getText();
    	//--
    	
    	Date actual = new Date();
		Date fechaSeleccionada = dateFecha.getDate();
		
		 if(tSala != null && tPelicula != null && hora != null && fecha != null
	        		&& cantLibres > 0 && precioUni.length() > 0){
			 if(actual.after(fechaSeleccionada)){
					if(actual.getYear() == fechaSeleccionada.getYear() && actual.getMonth() == fechaSeleccionada.getMonth()
							&& actual.getDate() == fechaSeleccionada.getDate()){
						Float precioUni_float = Float.parseFloat(precioUni);
			        	TSesion tSesion = new TSesion(tPelicula,tSala,fecha,hora,cantLibres,precioUni_float);
			            Controlador ctrl = Controlador.getInstancia();
			            setVisible(false);
			            ctrl.accion(tSesion, Controlador.ANADIR_SESION);
			            ctrl.accion(null, Controlador.VER_SESIONES);			
					}else{
						JOptionPane.showMessageDialog(null, "No puede introducir una fecha pasada");
					}	            	
		        }
				else{
					Float precioUni_float = Float.parseFloat(precioUni);
		        	TSesion tSesion = new TSesion(tPelicula,tSala,fecha,hora,cantLibres,precioUni_float);
		            Controlador ctrl = Controlador.getInstancia();
		            setVisible(false);
		            ctrl.accion(tSesion, Controlador.ANADIR_SESION);
		            ctrl.accion(null, Controlador.VER_SESIONES);
				}				
		 }
		 else{
			 JOptionPane.showMessageDialog(null, "No están todos los datos rellenos");
		 }
		
        
    }                                          

    

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox cbHorasDisponibles;
    private javax.swing.JComboBox cbPeliculas;
    private javax.swing.JComboBox cbSalas;
    private com.toedter.calendar.JDateChooser dateFecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableSesiones;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JSpinner spinnerCantLibres;
    private javax.swing.JTextField tPrecioUnitario;
    private javax.swing.JTextField txtDuracion;
    // End of variables declaration                   
}
