/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion.Sesion;

import Negocio.Sesion.TSesion;
import Presentacion.Controlador.Controlador;

import java.util.ArrayList;

/**
 *
 * @author gerar
 */
public class PanelSesionPorSala extends javax.swing.JPanel {

    /**
     * Creates new form PanelSesionPorSala
     */
    public PanelSesionPorSala(ArrayList<TSesion> tSesionesPorSala) {

        initComponents();
        
        this.setOpaque(false);
        //jTable1.setOpaque(false);
        /*jScrollPane1.setOpaque(false);
        jScrollPane1.getViewport().setOpaque(false);*/
        
        lblNombreSala.setText(tSesionesPorSala.get(0).gettSala().getNombre());
        final TableModelSesionPorSala tableModelSesionPorSala = new TableModelSesionPorSala(tSesionesPorSala);
        jTable1.setModel(tableModelSesionPorSala);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent e) {
                if(e.getClickCount()==2){
                    TSesion tSesionAux = (TSesion) tableModelSesionPorSala.gettSesionesPorSala().get(jTable1.getSelectedRow());
                    Controlador ctrl = Controlador.getInstancia();
                    ctrl.accion(tSesionAux.clone(), Controlador.VER_MODIFICAR_SESION);
                }
            }
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        lblNombreSala = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        lblNombreSala.setText("jLabel1");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNombreSala)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 591, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(lblNombreSala)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>                        


    // Variables declaration - do not modify                     
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblNombreSala;
    // End of variables declaration                   
}
