/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion.Pelicula;

import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

import Negocio.Pelicula.Imagen;
import Negocio.Pelicula.TPelicula;

import Presentacion.Controlador.Controlador;

import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
/**
 *
 * @author gerar
 */
public class GUIAnadirPelicula extends javax.swing.JDialog {
    protected Imagen fichero;

    /** 
     * @return the fichero
     * @generated "UML to Java (com.ibm.xtools.transform.uml2.java5.internal.UML2JavaTransform)"
     */
    public Imagen getFichero() {
            // begin-user-code
            return fichero;
            // end-user-code
    }

    /** 
     * @param fichero the fichero to set
     * @generated "UML to Java (com.ibm.xtools.transform.uml2.java5.internal.UML2JavaTransform)"
     */
    public void setFichero(Imagen fichero) {
            // begin-user-code
            this.fichero = fichero;
            // end-user-code
    }
    
    
    /**
     * Creates new form GUIAnadirPelicula1
     */
    public GUIAnadirPelicula(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        btnGroupEstado = new javax.swing.ButtonGroup();
        lblImg = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tClasificacion = new javax.swing.JTextField();
        spinnerDuracion = new javax.swing.JSpinner();
        tTitulo = new javax.swing.JTextField();
        rbHabilitada = new javax.swing.JRadioButton();
        rbDeshabilitada = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        btnExaminar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel2.setText("Titulo:");

        jLabel3.setText("Duracion:");

        jLabel4.setText("Clasificacion:");

        jLabel5.setText("Estado:");

        btnGroupEstado.add(rbHabilitada);
        rbHabilitada.setSelected(true);
        rbHabilitada.setText("Habilitada");

        btnGroupEstado.add(rbDeshabilitada);
        rbDeshabilitada.setText("Deshabilitada");

        jLabel6.setText("Imagen:");

        btnExaminar.setText("Examinar");
        btnExaminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExaminarActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblImg, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(spinnerDuracion)
                                    .addComponent(tTitulo)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbHabilitada)
                                .addGap(18, 18, 18)
                                .addComponent(rbDeshabilitada))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(tClasificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExaminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnGuardar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblImg, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(tTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(spinnerDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(tClasificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbHabilitada)
                            .addComponent(rbDeshabilitada))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(btnExaminar)
                    .addComponent(btnGuardar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void btnExaminarActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
        GUIFichero ventana = new GUIFichero(null, true);

        int resultado = ventana.getFileChooser().showOpenDialog(null);

        if (JFileChooser.APPROVE_OPTION == resultado) {
                File fileFichero = ventana.getFileChooser().getSelectedFile();

                fichero = new Imagen(Toolkit.getDefaultToolkit().getImage(
                                fileFichero.getAbsolutePath()),
                                fileFichero.getAbsolutePath());
                ImageIcon img = new ImageIcon(fichero.getImagen());
                Icon icono = new ImageIcon(img.getImage().getScaledInstance(
                                lblImg.getWidth(), lblImg.getHeight(), Image.SCALE_DEFAULT));
                lblImg.setIcon(icono);            
        }
    }                                           

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        boolean estado = false;
		String titulo = tTitulo.getText();
    	Integer duracion = (Integer) spinnerDuracion.getValue();
    	String clasificacion = tClasificacion.getText();
    	
    	if(titulo.compareToIgnoreCase("") != 0 && duracion > 0 && clasificacion.compareToIgnoreCase("") != 0 && fichero != null){
                if(rbHabilitada.isSelected()){
                        estado = true;
                }
                TPelicula tPelicula = new TPelicula(titulo,
                                duracion, clasificacion,
                                estado, fichero);
                Controlador ctrl = Controlador.getInstancia();
                ctrl.accion(tPelicula, Controlador.ANADIR_PELICULA);
                setVisible(false);
                ctrl.accion(null, Controlador.VER_PELICULAS);
        }else{
                JOptionPane.showMessageDialog(null, "No están todos los datos rellenos");
        }
    }                                          


    // Variables declaration - do not modify                     
    protected javax.swing.JButton btnExaminar;
    private javax.swing.ButtonGroup btnGroupEstado;
    protected javax.swing.JButton btnGuardar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    protected javax.swing.JLabel lblImg;
    protected javax.swing.JRadioButton rbDeshabilitada;
    protected javax.swing.JRadioButton rbHabilitada;
    protected javax.swing.JSpinner spinnerDuracion;
    protected javax.swing.JTextField tClasificacion;
    protected javax.swing.JTextField tTitulo;
    // End of variables declaration                   
}
