package Presentacion.Venta;


import java.util.Date;

import javax.swing.JOptionPane;

import Negocio.Sesion.TSesion;
import Negocio.Ventas.LineaVenta;
import Negocio.Ventas.TVenta;
import Presentacion.Controlador.Controlador;

public class PanelRealizarVenta extends javax.swing.JPanel {

    private LineaVenta lineaVenta;
    private TVenta tVenta;
    /**
     * Creates new form PanelModificarSala1
     */
    public PanelRealizarVenta(TVenta tVenta,LineaVenta lineaVenta) {
    	this.tVenta = tVenta;
        this.lineaVenta = lineaVenta;
        TSesion tSesion = lineaVenta.gettSesion();
        Integer cant = lineaVenta.getCant();
        initComponents();
        
        Pelicula.setText("Pelicula " + tSesion.gettPelicula().getTitulo());
        Pelicula.setEditable(false);
        Dia.setEditable(false);
        Sala.setEditable(false);
        Hora.setEditable(false);


        Dia.setText("Dia: " + tSesion.getFecha());

        Sala.setText("Sala: " + tSesion.gettSala().getNombre());

        Hora.setText("Hora: " + tSesion.getHora());
        SpinnerCantidad.setValue(cant);
        
        //lblNombreSala.setText("Pelicula" + tsesion.gettPelicula().getTitulo());
       // spinnerColumnas
       // spinnerFilas.setValue(tsesion.getPrecioUnitario());
        /*if (tSala.isEstado()) {
                rbHabilitado.setSelected(true);
        } else {
                rbDeshabilitado.setSelected(true);
        }*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
    	 SpinnerCantidad = new javax.swing.JSpinner();
         Cantidad = new javax.swing.JLabel();
         Guardar = new javax.swing.JButton();
         Cancelar = new javax.swing.JButton();
         Pelicula = new javax.swing.JTextField();
         Dia = new javax.swing.JTextField();
         Sala = new javax.swing.JTextField();
         Hora = new javax.swing.JTextField();
         TituloPanel = new javax.swing.JLabel();

         Cantidad.setText("Cantidad");

         Guardar.setText("Guardar");
         Guardar.addActionListener(new java.awt.event.ActionListener() {
             public void actionPerformed(java.awt.event.ActionEvent evt) {
            	 btnGuardarActionPerformed(evt);
             }
         });

         Cancelar.setText("Cancelar");

         
         

         TituloPanel.setText("Realizar venta:");

         javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
         this.setLayout(layout);
         layout.setHorizontalGroup(
             layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
             .addGroup(layout.createSequentialGroup()
                 .addGap(23, 23, 23)
                 .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(layout.createSequentialGroup()
                         .addGap(41, 41, 41)
                         .addComponent(Cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                         .addComponent(SpinnerCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                     .addComponent(TituloPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addGroup(layout.createSequentialGroup()
                         .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                             .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                 .addComponent(Pelicula, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                                 .addComponent(Sala))
                             .addComponent(Guardar))
                         .addGap(18, 18, 18)
                         .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                             .addComponent(Cancelar)
                             .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                 .addComponent(Dia)
                                 .addComponent(Hora, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)))))
                 .addContainerGap(80, Short.MAX_VALUE))
         );
         layout.setVerticalGroup(
             layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
             .addGroup(layout.createSequentialGroup()
                 .addGap(13, 13, 13)
                 .addComponent(TituloPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                 .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                     .addComponent(Pelicula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(Dia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                 .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                     .addComponent(Sala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(Hora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                 .addGap(18, 18, 18)
                 .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                     .addComponent(Cantidad)
                     .addComponent(SpinnerCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                 .addGap(18, 18, 18)
                 .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                     .addComponent(Guardar)
                     .addComponent(Cancelar))
                 .addContainerGap(130, Short.MAX_VALUE))
         );
    }// </editor-fold>                               

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    	//if(this.lineaVenta.gettSesion().getFecha())
    	Date fecha_venta = new Date();
    	fecha_venta.setDate(lineaVenta.gettSesion().getFecha().getDate());
    	fecha_venta.setHours(lineaVenta.gettSesion().getHora().getHours());
    	Date fecha_actual = new Date();
    	int cantidad = (int) SpinnerCantidad.getValue();
    	if(cantidad > 0 && lineaVenta != null){
    		lineaVenta.setCant((int) SpinnerCantidad.getValue());
        	tVenta.modificarSesion(lineaVenta);
        	System.out.println(fecha_venta);
        	Controlador.getInstancia().accion(tVenta, Controlador.VER_VENTAS);
    	}
    	/*else if(fecha_actual.compareTo(fecha_venta) > 0){
    		JOptionPane.showMessageDialog(null, "No puede introducir una fecha pasada");
        }*/
    	else
    	JOptionPane.showMessageDialog(null, "No están todos los datos rellenos");
    	
    }                                             
    

    public LineaVenta getLineaVenta() {
		return lineaVenta;
	}

	public void setLineaVenta(LineaVenta lineaVenta) {
		this.lineaVenta = lineaVenta;
	}




	// Variables declaration - do not modify                     
    private javax.swing.JButton Cancelar;
    private javax.swing.JLabel Cantidad;
    private javax.swing.JTextField Dia;
    private javax.swing.JButton Guardar;
    private javax.swing.JTextField Pelicula;
    private javax.swing.JTextField Sala;
    private javax.swing.JSpinner SpinnerCantidad;
    private javax.swing.JLabel TituloPanel;
    private javax.swing.JTextField Hora;
    // End of variables declaration                   
}
