/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion.Venta;

import Negocio.Pelicula.TPelicula;
import Negocio.Sesion.TSesion;
import Negocio.Ventas.TVenta;
import Presentacion.Controlador.Controlador;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.BoxLayout;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;

/**
 *
 * @author gerar
 */
public class PanelVentaPeliculaSesiones extends javax.swing.JPanel {
    private JButtonSesion buttonSeleccionado;
    private TVenta tVenta;
    /**
     * Creates new form PanelVentaPeliculaSesiones
     */
    public PanelVentaPeliculaSesiones(TVenta tVenta,TPelicula tPelicula,ArrayList<TSesion> tSesiones) {
        initComponents();
        this.tVenta = tVenta;
        lblNombre.setText(tPelicula.getTitulo());
        lblDuracion.setText(tPelicula.getDuracion().toString());
        lblClasificacion.setText(tPelicula.getClasificacion());
        ImageIcon img = new ImageIcon(tPelicula.getImagen().getImagen());
        Icon icono = new ImageIcon(img.getImage().getScaledInstance(90, 140, Image.SCALE_DEFAULT));
        lblImagenPelicula.setIcon(icono);
        ArrayList<TSesion> tSesionesPorSala = new ArrayList();
        final ArrayList<JButton> botonesSesion = new ArrayList();
        panelSesionesPelicula.setLayout(new BoxLayout(panelSesionesPelicula, BoxLayout.Y_AXIS));
        
        if(!tSesiones.isEmpty()){
            TSesion tSesionAux = tSesiones.get(0);
            tSesionesPorSala.add(tSesionAux);
            for (int i = 1; i < tSesiones.size(); i++) {
                if(tSesiones.get(i).gettSala().getIdSala() == tSesionAux.gettSala().getIdSala()){
                    tSesionesPorSala.add(tSesiones.get(i));
                }else{
                    PanelVentaSesionesPorSala panelSesionPorSala = new PanelVentaSesionesPorSala(tSesionesPorSala);
                    ArrayList<JButtonSesion> botonesSesionAux = panelSesionPorSala.getBotonesSesion();
                    for (JButton jButton : botonesSesionAux) {
                        jButton.addActionListener(new ActionListener(){
                            @Override
                            public void actionPerformed(ActionEvent e) {
                                for (JButton jButton2 : botonesSesion) {
                                    jButton2.setEnabled(true);
                                }
                                JButtonSesion btn = (JButtonSesion)(JButton)e.getSource();
                                btn.setEnabled(false);
                                buttonSeleccionado = btn;
                            }                           
                        });
                    }
                    botonesSesion.addAll(botonesSesionAux);
                    panelSesionPorSala.setSize(585,74);
                    panelSesionesPelicula.add(panelSesionPorSala);
                    tSesionesPorSala = new ArrayList();
                    tSesionesPorSala.add(tSesiones.get(i));
                }
            }
            if(!tSesionesPorSala.isEmpty()){
                PanelVentaSesionesPorSala panelSesionPorSala = new PanelVentaSesionesPorSala(tSesionesPorSala);
                ArrayList<JButtonSesion> botonesSesionAux = panelSesionPorSala.getBotonesSesion();
                for (JButton jButton : botonesSesionAux) {
                    jButton.addActionListener(new ActionListener(){
                        @Override
                        public void actionPerformed(ActionEvent e) {
                            for (JButton jButton2 : botonesSesion) {
                                jButton2.setEnabled(true);
                            }
                            JButtonSesion btn = (JButtonSesion)(JButton)e.getSource();
                            btn.setEnabled(false);
                            buttonSeleccionado = btn;
                        }                           
                    });                    
                }
                botonesSesion.addAll(botonesSesionAux);
                panelSesionPorSala.setSize(585,74);
                panelSesionesPelicula.add(panelSesionPorSala);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        lblImagenPelicula = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblDuracion = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblClasificacion = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelSesionesPelicula = new javax.swing.JPanel();
        btnAtras = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        spinnerCant = new javax.swing.JSpinner();
        btnAnadir = new javax.swing.JButton();

        jLabel2.setText("Nombre:");

        lblNombre.setText("jLabel3");

        jLabel3.setText("Duracion:");

        lblDuracion.setText("jLabel4");

        jLabel4.setText("Clasificacion:");

        lblClasificacion.setText("jLabel5");

        javax.swing.GroupLayout panelSesionesPeliculaLayout = new javax.swing.GroupLayout(panelSesionesPelicula);
        panelSesionesPelicula.setLayout(panelSesionesPeliculaLayout);
        panelSesionesPeliculaLayout.setHorizontalGroup(
            panelSesionesPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 578, Short.MAX_VALUE)
        );
        panelSesionesPeliculaLayout.setVerticalGroup(
            panelSesionesPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 213, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(panelSesionesPelicula);

        btnAtras.setText("Atras");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        jLabel1.setText("Cantidad:");

        btnAnadir.setText("Añadir");
        btnAnadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnadirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblImagenPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNombre)
                                    .addComponent(lblDuracion)
                                    .addComponent(lblClasificacion)))
                            .addComponent(btnAtras))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spinnerCant, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAnadir)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnAtras)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(lblNombre))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(lblDuracion))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(lblClasificacion)))
                    .addComponent(lblImagenPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(spinnerCant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAnadir)))
        );
    }// </editor-fold>                        

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        
        Controlador.getInstancia().accion(null, Controlador.REALIZAR_NUEVA_VENTA);
    }                                        

    private void btnAnadirActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        TSesion tSesion = buttonSeleccionado.gettSesion();
        Integer cant = (Integer) spinnerCant.getValue();
        //SingletonVenta.getInstancia().anadirSesion(tSesion, cant);
        tVenta.anadirSesion(tSesion, cant);
        Controlador.getInstancia().accion(tVenta, Controlador.VER_VENTAS);
    }                                         


    // Variables declaration - do not modify                     
    private javax.swing.JButton btnAnadir;
    private javax.swing.JButton btnAtras;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblClasificacion;
    private javax.swing.JLabel lblDuracion;
    private javax.swing.JLabel lblImagenPelicula;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JPanel panelSesionesPelicula;
    private javax.swing.JSpinner spinnerCant;
    // End of variables declaration                   
}
