/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion.Venta;

import Negocio.Sesion.TSesion;
import java.awt.Color;
import java.awt.FlowLayout;
import java.util.ArrayList;
import java.util.Date;

/**
 *
 * @author gerar
 */
public class PanelVentaSesionesPorSala extends javax.swing.JPanel {
    private ArrayList<JButtonSesion> botonesSesion;
    /**
     * Creates new form PanelVentaSesionesPorSala
     */
    public PanelVentaSesionesPorSala(ArrayList<TSesion> tSesionesPorSala) {
        initComponents();
        lblNombreSala.setText(tSesionesPorSala.get(0).gettSala().getNombre());
        FlowLayout layout = new FlowLayout();
        layout.setAlignment(FlowLayout.LEFT);
        panelSesionesPelicula.setLayout(layout);
        botonesSesion = new ArrayList();
        for (TSesion tSesion : tSesionesPorSala) {
            Date hora = tSesion.getHora();
            JButtonSesion btn = new JButtonSesion(tSesion);
            botonesSesion.add(btn);
            //label.setPreferredSize(new Dimension(35,50));
            btn.setBackground(Color.red);
            panelSesionesPelicula.add(btn);
        }
    }
    
    public ArrayList<JButtonSesion> getBotonesSesion(){
        return botonesSesion;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        lblNombreSala = new javax.swing.JLabel();
        panelSesionesPelicula = new javax.swing.JPanel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblNombreSala.setText("jLabel1");

        javax.swing.GroupLayout panelSesionesPeliculaLayout = new javax.swing.GroupLayout(panelSesionesPelicula);
        panelSesionesPelicula.setLayout(panelSesionesPeliculaLayout);
        panelSesionesPeliculaLayout.setHorizontalGroup(
            panelSesionesPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelSesionesPeliculaLayout.setVerticalGroup(
            panelSesionesPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 42, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNombreSala)
                        .addGap(0, 537, Short.MAX_VALUE))
                    .addComponent(panelSesionesPelicula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(2, 2, 2))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(lblNombreSala)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelSesionesPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4))
        );
    }// </editor-fold>                        


    // Variables declaration - do not modify                     
    private javax.swing.JLabel lblNombreSala;
    private javax.swing.JPanel panelSesionesPelicula;
    // End of variables declaration                   
}
