/*
,, * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion.Venta;

import Negocio.Empleados.TEmpleado;
import Negocio.Ventas.LineaVenta;
import Negocio.Ventas.TVenta;
import Presentacion.Controlador.Controlador;

import java.util.ArrayList;

import javax.swing.JComboBox;

/**
 *
 * @author gerar
 */
public class PanelModificarVenta extends javax.swing.JPanel {
    private TableModelVentas tableModel;
    private TVenta tVenta;
    private ArrayList<TEmpleado> tEmpleados;
    /**
     * Creates new form PanelModificarVenta
     */
    public PanelModificarVenta(final TVenta tVenta,final ArrayList<TEmpleado> tEmpleados) {
        initComponents();
        this.tVenta = tVenta;
        this.tEmpleados = tEmpleados;
        tableModel = new TableModelVentas(tVenta);
        tableLineaVenta.setModel(tableModel);
        tableLineaVenta.getTableHeader().setReorderingAllowed(false);

        tableLineaVenta.setOpaque(false);
        jScrollPane1.setOpaque(false);
        jScrollPane1.getViewport().setOpaque(false);
        this.setOpaque(false);
        panelModificarLineaVenta.setOpaque(false);
        for (TEmpleado tEmpleado : tEmpleados) {
			cbEmpleados.addItem(tEmpleado.getDni());
		}
        if(tVenta.gettEmpleado() != null){
     	   cbEmpleados.setSelectedItem(tVenta.gettEmpleado().getDni());
        }else{
     	   TEmpleado tEmpleadoSeleccionado = tEmpleados.get(cbEmpleados.getSelectedIndex());
     	   tVenta.asignarVendedor(tEmpleadoSeleccionado);
        }
        cbEmpleados.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
         	   TEmpleado tEmpleadoSeleccionado = tEmpleados.get(cbEmpleados.getSelectedIndex());
                tVenta.asignarVendedor(tEmpleadoSeleccionado);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableLineaVenta = new javax.swing.JTable();
        panelModificarLineaVenta = new javax.swing.JPanel();
        btnAnadirSesion = new javax.swing.JButton();
        btnEliminarSesion = new javax.swing.JButton();
        btnFinalizarVenta = new javax.swing.JButton();
        cbEmpleados = new javax.swing.JComboBox<String>();

        jPanel1.setPreferredSize(new java.awt.Dimension(600, 411));

        tableLineaVenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableLineaVenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableLineaVentaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableLineaVenta);

        panelModificarLineaVenta.setPreferredSize(new java.awt.Dimension(490, 200));

        javax.swing.GroupLayout panelModificarLineaVentaLayout = new javax.swing.GroupLayout(panelModificarLineaVenta);
        panelModificarLineaVenta.setLayout(panelModificarLineaVentaLayout);
        panelModificarLineaVentaLayout.setHorizontalGroup(
            panelModificarLineaVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
        );
        panelModificarLineaVentaLayout.setVerticalGroup(
            panelModificarLineaVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        btnAnadirSesion.setText("Añadir Sesion");
        btnAnadirSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnadirSesionActionPerformed(evt);
            }
        });

        btnEliminarSesion.setText("Eliminar Sesion");
        btnEliminarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarSesionActionPerformed(evt);
            }
        });

        btnFinalizarVenta.setText("Finalizar Venta");
        btnFinalizarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarVentaActionPerformed(evt);
            }
        });

        cbEmpleados.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbEmpleadosItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(panelModificarLineaVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnEliminarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnFinalizarVenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAnadirSesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(1, 10, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(cbEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAnadirSesion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminarSesion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                        .addComponent(btnFinalizarVenta)
                        .addContainerGap())
                    .addComponent(panelModificarLineaVenta, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 609, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 609, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 411, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>                        

    private void tableLineaVentaMouseClicked(java.awt.event.MouseEvent evt) {                                             
        // TODO add your handling code here:
        LineaVenta lineaVenta = tableModel.getSelectedLineaVenta(tableLineaVenta.getSelectedRow());
        Object[] datos = new Object[2];
        datos[0] = tVenta;
        datos[1] = lineaVenta;
        Controlador.getInstancia().accion(datos, Controlador.VER_VENTAS_VER_MODIFICAR);
    }                                            

    private void btnAnadirSesionActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:
        Controlador.getInstancia().accion(tVenta, Controlador.REALIZAR_NUEVA_VENTA);
    }                                               

    private void btnEliminarSesionActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        // TODO add your handling code here:
        LineaVenta lineaVenta = tableModel.getSelectedLineaVenta(tableLineaVenta.getSelectedRow());
        tVenta.borrarSesion(lineaVenta.gettSesion());
        Controlador.getInstancia().accion(tVenta, Controlador.VER_VENTAS);
    }                                                 

    private void btnFinalizarVentaActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        // TODO add your handling code here:
        Controlador.getInstancia().accion(tVenta, Controlador.CERRAR_VENTA);
    }                                                 

    private void cbEmpleadosItemStateChanged(java.awt.event.ItemEvent evt) {                                             
        // TODO add your handling code here:
    }                                            


    // Variables declaration - do not modify                     
    private javax.swing.JButton btnAnadirSesion;
    private javax.swing.JButton btnEliminarSesion;
    private javax.swing.JButton btnFinalizarVenta;
    private JComboBox<String> cbEmpleados;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelModificarLineaVenta;
    private javax.swing.JTable tableLineaVenta;
    // End of variables declaration                   
}

