/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion.Sala;

import javax.swing.JOptionPane;

import Negocio.Sala.TSala;
import Presentacion.Controlador.Controlador;

/**
 *
 * @author gerar
 */
public class PanelModificarSala extends javax.swing.JPanel {

    private TSala tSala;
    /**
     * Creates new form PanelModificarSala1
     */
    public PanelModificarSala(TSala tSala) {
        initComponents();
        this.tSala = tSala;
        lblNombreSala.setText(tSala.getNombre());
        spinnerColumnas.setValue(tSala.getColumnas());
        spinnerFilas.setValue(tSala.getFilas());
        if (tSala.isEstado()) {
                rbHabilitado.setSelected(true);
        } else {
                rbDeshabilitado.setSelected(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        btnGroupEstado = new javax.swing.ButtonGroup();
        lblNombreSala = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        spinnerColumnas = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        spinnerFilas = new javax.swing.JSpinner();
        rbHabilitado = new javax.swing.JRadioButton();
        rbDeshabilitado = new javax.swing.JRadioButton();
        btnGuardar = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Modificar Sala", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.ABOVE_TOP));

        lblNombreSala.setText("jLabel1");

        jLabel2.setText("Columnas:");

        jLabel3.setText("Filas:");

        btnGroupEstado.add(rbHabilitado);
        rbHabilitado.setText("Habilitado");

        btnGroupEstado.add(rbDeshabilitado);
        rbDeshabilitado.setText("Deshabilitado");

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(lblNombreSala))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbHabilitado)
                                .addGap(99, 99, 99)
                                .addComponent(rbDeshabilitado))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(spinnerColumnas, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                                    .addComponent(spinnerFilas))))))
                .addContainerGap(153, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnGuardar)
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(lblNombreSala)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(spinnerColumnas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(spinnerFilas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbHabilitado)
                    .addComponent(rbDeshabilitado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGuardar)
                .addContainerGap(42, Short.MAX_VALUE))
        );
    }// </editor-fold>                        

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    	
    	int Columnas = (int)spinnerColumnas.getValue();
    	int Filas = (int) spinnerFilas.getValue();
    	if(Columnas > 0 && Filas > 0 && (rbHabilitado.isSelected() || rbDeshabilitado.isSelected())){
    		tSala.setColumnas(Columnas);
    		tSala.setFilas(Filas);
    		 if (rbHabilitado.isSelected()) {
                 tSala.setEstado(true);
         } else {
                 tSala.setEstado(false);
         }
         Controlador ctrl = Controlador.getInstancia();
         ctrl.accion(tSala, Controlador.MODIFICAR_SALA);
         ctrl.accion(null, Controlador.VER_SALAS);
    	}else{
			JOptionPane.showMessageDialog(null, "No están todos los datos rellenos");
		}
    	
       
    }                                          


    // Variables declaration - do not modify                     
    private javax.swing.ButtonGroup btnGroupEstado;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblNombreSala;
    private javax.swing.JRadioButton rbDeshabilitado;
    private javax.swing.JRadioButton rbHabilitado;
    private javax.swing.JSpinner spinnerColumnas;
    private javax.swing.JSpinner spinnerFilas;
    // End of variables declaration                   
}
